name: Deploy to Firebase Hosting
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_deploy:
    if: ${{ github.event_name == 'push' || (github.event.pull_request.head.repo.full_name == github.repository) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # If you're using a framework that needs building (React/Vue/etc), 
      # add these steps back. For plain HTML, you don't need them.
      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '18'
      # - name: Install dependencies
      #   run: npm ci
      # - name: Build
      #   run: npm run build
      
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CEDARRAPIDSSTEMCIRCLE }}
          projectId: cedarrapidsstemcircle